webapp/weather/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField
from wtforms.fields.html5 import DateField
from datetime import datetime

class WeatherForm(FlaskForm):
    city_name = StringField("Ведите название города", render_kw={"class": "form-control"})
    date = DateField('Выберите дату', format='%Y-%m-%d')
    submit = SubmitField('Получит прогноз', render_kw={"class": "btn btn-primary"})

webapp/__init__.py
from flask import Flask, render_template, url_for, request, redirect, flash
from webapp.weather.forms import WeatherForm
from webapp.weather.views import blueprint as weather_blueprint

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')

    app.register_blueprint(weather_blueprint)

    @app.route('/')
    def weather_process():
        form = WeatherForm()
        return render_template('index.html', form = form)

    return app
    
    

webapp/weather/views.py
from flask import render_template, url_for, redirect, flash, Blueprint
from utils import api_weather
from datetime import datetime, timedelta
from webapp.weather.forms import WeatherForm
import datetime

blueprint = Blueprint('weather', __name__, url_prefix='')

@blueprint.route('/process', methods=['POST'])
def process_process():
    form = WeatherForm()
    if form.validate_on_submit:
        city_name = form.city_name.data
        date = form.date.data
        now = datetime.date.today()
        if city_name == '':
            flash('Введите город')
            return redirect(url_for('weather_process'))
        if date is None:
            date = 'today'
        elif date < now:
            flash('Проверьте дату, прогноз актуален на сегодняшний день и ближайшие пять дней вперед')
            return redirect(url_for('weather_process'))
        elif date > now + timedelta(days=5):
            flash('Проверьте дату, прогноз актуален на сегодняшний день и ближайшие пять дней вперед')
            return redirect(url_for('weather_process'))
        weather = api_weather(city_name, date)
        if 'error' in weather['data']:
            flash('Проверьте город')
            return redirect(url_for('weather_process'))
        weather_today = weather['data']['current_condition'][0]['temp_C']
        weather_on_date = weather['data']['weather'][0]['maxtempC']
        if weather:
            return render_template('weather.html', weather_today = weather_today, 
                                    weather_on_date = weather_on_date, date = date, city_name = city_name)
        else:
            flash('Сервер погоды временно не доступен')
    return redirect(url_for('weather_process'))

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{{ url_for("static", filename="site/assets/vendor/bootstrap/bootstrap.min.css") }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for("static", filename="site/assets/css/lazy.css") }}">
        <link rel="stylesheet" href="{{ url_for("static", filename="style.css") }}">
    <title>{{ page_title }}</title>
  </head>
  <body>
    <!-- your content here -->
    {% include 'menu.html' %}
    <div class="col-4"></div>
    <div class="conainer">
        {% block content %}{% endblock  %}
    </div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{ url_for("static", filename="site/assets/vendor/jquery/jquery.min.js") }}"></script>
    <script src="{{ url_for("static", filename="site/assets/vendor/popper/popper.min.js") }}"></script>
    <script src="{{ url_for("static", filename="site/assets/vendor/bootstrap/bootstrap.min.css") }}" ></script>

    <!-- optional plugins -->
    <script src="{{ url_for("static", filename="site/assets/vendor/nouislider/js/nouislider.min.js") }}"></script>

    <!--   lazy javascript -->
    <script src="{{ url_for("static", filename="site/assets/js/lazy.js") }}"></script>
  </body>
  <div class="container">
		<div class="wrapper">	
			<div class="footer">
				<i class="fab fa-linkedin-in"></i>
				<a href="https://www.linkedin.com/in/yauhen-ranko-63a7801a3/">Linkedin</a> <br>
				<i class="fab fa-facebook-square"></i>
				<a href="https://www.facebook.com/yauhen.ranko">facebook</a> <br>
			</div>
		</div>
	</div>	
</html>

webapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% include('messages.html') %}
	<div class="container">
		<div class="row">
			<div class="col-4">
				<form action="{{ url_for('weather.process_process') }}" method="POST">
						<div class="form-group">
							{{ form.city_name.label }}<br>
							{{ form.city_name() }}
						</div>
						<div class="form-group">
							{{ form.date.label }}<br>
							{{ form.date() }}
							<p class="small my-4 text-center">Прогноз погоды на сегодняшний и ближайшие 5 дней </p>
						</div>
							{{ form.submit }} <br>
				</form>
			</div>
			<div class="col-6">
				{% if weather %}
					{{ weather_today }}
					
				{% endif %}
			</div>
		</div>
	</div>	
{% endblock  %}

webapp/templates/menu.html
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center" href="{{ url_for('weather_process') }}">Погода</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown-1" aria-controls="navbarNavDropdown-1"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNavDropdown-1">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="https://drive.google.com/file/d/1a-x_gI01x3zn3ZtPWCJR9b8YKdVAp3qc/view?usp=sharing">Видео использования
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/YauhenRanko/yandex_cloud_test">GitHub</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}

webapp/templates/weather.html
{% extends 'base.html' %}

{% block content %}
    <div class="row"> 
            <div class="col-8">
                {% if date == 'today'  %}
                    <h2>{{ city_name }}</h2> <br> <hr> 
                    <h4> Сегодня температура воздуха - {{ weather_today }} градусов по цельсию </h4>                             
                {% else %}
                    <h2>{{ city_name }}</h2> <br> <hr> 
                    <h4>Погода на {{ date }} - {{ weather_on_date }} градусов по цельсию</h4>   
                {% endif %}                                
	        </div>
            <div class="col-6">
                    
            </div>
    </div>  

	{% endblock  %}